local array = require("array")

local demo = array()
demo:push(1)
demo:output()
demo:push(2)
demo:output()
demo:insert(1, 3)
demo:output()
demo:remove(1)
demo:output()
demo:pop()
demo:output()
demo:clear()
demo:output()