local list = require("list")

local demo = list()
local node1 = demo:push(1)
demo:output()
local node2 = demo:push(2)
demo:output()
local node3 = demo:insert(node1, 3)
demo:output()
demo:remove(node2)
demo:output()
local nodeHead = demo:getHead()
print(nodeHead.value)
local nodeTail = demo:getTail()
print(nodeTail.value)
local _pre = nodeTail:getPre()
print(_pre.value)
local _next = nodeHead:getNext()
print(_next.value,"\n********************")
demo:popAll()
demo:output()